# CONFIGURACIÓN DEL SERVIDOR
server.port=8080

spring.datasource.url=jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-santiago-1.oraclecloud.com))(connect_data=(service_name=gacb052b0e9cc83_dbcursos_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
spring.datasource.username=ADMIN
spring.datasource.password=Duoc_2026_inscripciones
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

# SEGURIDAD: OAUTH2 RESOURCE SERVER (AZURE AD B2C)
# Reemplaza 'tu-tenant-b2c' por el nombre de tu dominio B2C y 'tu-politica-flujo' por el nombre del flujo de usuario (ej: B2C_1_signupsignin)
# spring.security.oauth2.resourceserver.jwt.issuer-uri=https://tu-tenant-b2c.b2clogin.com/tu-tenant-b2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=tu-politica-flujo

# CONFIGURACIÓN AWS S3 (CREDANCIALES TEMPORALES DE AWS ACADEMY)
# CONFIGURACIÓN EXACTA PARA S3 CONFIG
aws.access.key.id=ASIAS7V7MX567GS7BDWC
aws.secret.key=8OS7uJt4JIrlqWk+fPBndFxf+/4xbHqZINbI8ys4
aws.session.token=IQoJb3JpZ2luX2VjELz//////////wEaCXVzLXdlc3QtMiJHMEUCIQCO/Lq6gSSS/2iSNOUUBIz1RwzJSrTsgV0sgQsjcXwAUgIgX+Tj/rOhie6FYLEvuF1mB984mEjcG+h/0KZ67+xCVBQqugIIhP//////////ARABGgwyMDU0ODYwNzk4NjkiDJ0XLOURy9OwnJEBRSqOAr4ddKEswEsTSyleSOYR18KQoLx5R05cT8F+sSbOUprkINvWxqHqXM7bwg8kqpP/sR+x5rFrXi/iIU2bU6ke3lP7+Ef0LREvPcs784Rx71ILirtwR5eAy1xlmUEe+Qp6tkRKapopdHQoBcmI4Aw8J6cC4EMY5ZBQTbIfqJ1RIDlCe+KuqY6VNRueRq+eaf2vLMLHJEyE83KvUEycIkQohmnPdJPfp2uqmZoEAXp99YA7ONJtYsR7krQrPZMVSb1wPXru3rhwwIlalWOLIwrVCLVU5LwZ2bK5mMQ+bs4zbXws4BRhq2oJ57xExYQ7IGz+PVlu3ZKjodKgcTs0PE2H1zKeTaqvhbxfxa7jVG/mtDC6xIDSBjqdAYs7hvnKDkHiP6D4K1e5HPJaNam2d/9enbdwdiqSMSx57qXadw0aNsqvJLm2UWf2jcircyKObu+XGFsmSw+H9JPHfBUBj6/v5ppGdcb9dtw08kOaMFiMsPdCkHi3ARQDo/sziEwu+HZOY7YKcoiBkjF19IeprFLFN2O0Aalaj3QZFJgk4h1yS3nmbBwjBoFAG2oeAeY+RrRbkl1LRrE=
aws.s3.region=us-east-1
aws.s3.bucket-name=duoc-inscripciones-bucket-cristian-olivares