# ===================================================================
# PERSISTENCIA ORACLE CLOUD (SEMANA 1)
# ===================================================================
# Dirección de conexión usando la descripción nativa completa
spring.datasource.url=jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-santiago-1.oraclecloud.com))(connect_data=(service_name=gacb052b0e9cc83_dbcursos_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))

# Credenciales de acceso a la Base de Datos
spring.datasource.username=ADMIN
spring.datasource.password=Duoc_2026_inscripciones
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuración mTLS apuntando a la carpeta interna del proyecto (Rutas relativas)
spring.datasource.hikari.data-source-properties.javax.net.ssl.trustStore=./OracleWallet/truststore.jks
spring.datasource.hikari.data-source-properties.javax.net.ssl.trustStorePassword=Duoc_2026
spring.datasource.hikari.data-source-properties.javax.net.ssl.keyStore=./OracleWallet/keystore.jks
spring.datasource.hikari.data-source-properties.javax.net.ssl.keyStorePassword=Duoc_2026

# Inicialización automática de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===================================================================
# CONFIGURACIÓN AMAZON AWS S3 (SEMANA 2)
# ===================================================================
# @define-configuration-properties
aws.s3.access-key=TU_ACCESS_KEY_AQUÍ
aws.s3.secret-key=TU_SECRET_KEY_AQUÍ
aws.s3.session-token=TU_SESSION_TOKEN_AQUÍ
aws.s3.region=us-east-1
aws.s3.bucket-name=duoc-inscripciones-bucket-cristian-olivares